WeblateOrg/website

- weblate_web/html/features.html
Found while translating Weblate to Hebrew.
> Fixed typo

- weblate_web/templates/features.html
As per https://www.gnu.org/software/gettext/ and https://en.wikipedia.org/wiki/Gettext
Also, https://github.com/WeblateOrg/weblate/pull/2089
> Spelling: , gettext

- weblate_web/templates/support.html
Fixes #2070
Also, https://github.com/WeblateOrg/weblate/pull/2087
> Spelling: Chosen users

- .scrutinizer.yml
There is some issue with utf8...
> Fix tests on Scrutinizer

- weblate_web/templates/contribute.html
- weblate_web/templates/download.html
* Improvements to the contribute page.
* Small reorg of the download page.
Live version: https://betaweb.weblate.org/en/contribute/
Feedback welcome (cc @comradekingu)
> Update website content

- weblate_web/templates/hosting-free.html
Spotted by @rffontenelle in https://hosted.weblate.org/translate/weblate/website/pt_BR/?checksum=475ec887e7abbfff#comments :)
> Spelling: Libre software

- weblate_web/templates/about.html
- weblate_web/templates/donate.html
- weblate_web/templates/features.html
- weblate_web/templates/support.html
One error spotted by @rffontenelle on Weblate. :)
New website https://betaweb.weblate.org
> WIP: New strings, second pass

- weblate_web/templates/donate.html
- weblate_web/templates/index.html
- weblate_web/templates/snippets/languages.html
- weblate_web/templates/support.html
"anually" spotted by T.Shimazaki at Hosted Weblate :)
> Small spellery

- weblate_web/templates/donate/form.html
- weblate_web/templates/download.html
- weblate_web/templates/features.html
- weblate_web/templates/hosting.html
- weblate_web/templates/snippets/about.html
- weblate_web/templates/snippets/features-2.html
- weblate_web/templates/snippets/pricing.html
- weblate_web/templates/snippets/vat.html
- weblate_web/templates/support.html
".NET" spotted by @rffontenelle :) As per https://en.wikipedia.org/wiki/.NET_Framework
> Small savings

- weblate_web/templates/about.html
- weblate_web/templates/base.html
- weblate_web/templates/donate.html
- weblate_web/templates/features.html
- weblate_web/templates/hosting.html
- weblate_web/templates/snippets/about.html
- weblate_web/templates/snippets/box-donate.html
- weblate_web/templates/support.html
- weblate_web/templates/user.html
- weblate_web/views.py
I think the language quality is good to go now. Just needs that nice donation message.
> Language polish

- weblate_web/templates/user.html
Not 100% sure about the service period string
> Spelling: Exceeds selected service period, –

- weblate_web/templates/hosting.html
My apologies, this slipped through quite a few cracks.
> Spelling: getting

- weblate_web/templates/payment/pending.html
As per https://en.wikipedia.org/wiki/Pro_forma
Both are allowed, but this is aligns with the latin origin.
> Spelling: Please follow the provided, pro forma

- weblate_web/templates/hosting.html
Not sure what things are limited, vs. what customization can be made
> Spelling: Default setup vs. dedicated

- weblate_web/templates/features.html
As per https://wiki.mozilla.org/WebExtensions (?) and https://en.wikipedia.org/wiki/Inno_Setup
> Spelling: Inno Setup, WebExtentions, tablets, fine-tune

- weblate_web/templates/donate/form.html
Fixed a small typo found in the source files:
immediatelly ⇒ immediately
> Fix small typo

- weblate_web/templates/support.html
Thanks in advance for reviewing.
> Fix minor typo

- weblate_web/static/style-rtl.css
- weblate_web/static/style.css
- weblate_web/templates/about.html
> About page - added team section

- weblate_web/templates/mail/subscription_intro.html
> Added missing p

- weblate_web/templates/mail/subscription_intro.html
Curiously "your Weblate" is also "… installation", "… instance", "… server" and "… deployment".
https://hosted.weblate.org/languages/nb_NO/weblate/search/?page=1&limit=100&q=your+weblate&sort_by=-priority%2Cposition
> Spelling: ending dot removed, the following

- weblate_web/templates/base.html
> Spelling: Licensed GPLv3+

- weblate_web/templates/about.html
simplification and clarification of *about team* sentences
> rewording about team

- weblate_web/models.py
- weblate_web/templates/snippets/service.html
changed button texts and added line breaks
> formatting and button wording

- weblate_web/templates/snippets/service.html
Works for noun and verb. Not sure where this is used.
> Spelling: Invite e-mail

- weblate_web/templates/about.html
team snippets were rewritten for better language and readability.
> team snippets improvements, `about` article punctuation correction

- weblate_web/models.py
Unsupported image type: %s → %s is not a supported image type?
"Article image, 1200x630 pixels" doesn't quite follow the format of the others. (Maybe that is OK.)
> Models.py language reworked

- weblate_web/models.py
> spelling correction in models.py

- weblate_web/templates/hosting.html
This is my mistake from 4 years ago.
People also have a hard time finding it, or somehow understanding what it says.
> Explanation of libre project hosting

- weblate_web/templates/base.html
- weblate_web/templates/privacy.html
- weblate_web/tests.py
- weblate_web/urls.py
This is now required by the payment gateway.
> feat: use separate view for privacy policy

- payments/models.py
- weblate_web/management/commands/process_payments.py
- weblate_web/management/commands/recurring_payments.py
- weblate_web/models.py
- weblate_web/settings.py
- weblate_web/tests.py
- weblate_web/views.py
This does exist for hosted.weblate.org integration, but there is no need to do this internally.
> feat: avoid triggering payments remotely from a single system

- .github/workflows/test.yml
> chore(ci): test with Python 3.13

- .github/workflows/test.yml
- .gitignore
- pyproject.toml
- requirements-test.txt
> chore: ci use pytest to execute testsuite

- weblate_web/templatetags/downloads.py
> chore: type annotate and simplify template tags

- weblate_web/payments/tests.py
- weblate_web/tests.py
This is no longer needed since we no loger use multiple databases.
> chore(tests): remove databases specification

- weblate_web/payments/backends.py
- weblate_web/payments/utils.py
- weblate_web/settings.py
> chore: add type annotations to backends

- weblate_web/payments/backends.py
- weblate_web/payments/tests.py
- weblate_web/views.py
- test backend including error states
- gracefully handle errors in views
> feat(backends): add tests for new backend

- weblate_web/payments/backends.py
- weblate_web/views.py
> fix(api): capture errors using sentry

- weblate_web/payments/backends.py
- weblate_web/payments/tests.py
Improve error handling in The Pay 2.0 and add tests coverage.
> feat(backends): improve error handling

- weblate_web/models.py
- weblate_web/settings.py
This makes type checking possible.
> chore: expand ssh settings ot not use dict/kwargs

- weblate_web/admin.py
- weblate_web/forms.py
- weblate_web/management/commands/recurring_payments.py
- weblate_web/management/commands/zammad_spam.py
- weblate_web/management/commands/zammad_sync.py
- weblate_web/models.py
- weblate_web/payments/tests.py
- weblate_web/remote.py
- weblate_web/settings.py
- weblate_web/templatetags/downloads.py
- weblate_web/templatetags/site_url.py
- weblate_web/tests.py
- weblate_web/urls.py
- weblate_web/views.py
> feat: improve mypy hints

- .github/workflows/mypy.yml
> feat(ci): enforce type checking

- requirements.txt
- schemas/money-s3/_Document.xsd
- schemas/money-s3/_Export.xsd
- schemas/money-s3/_Import.xsd
- schemas/money-s3/_Report.xsd
- schemas/money-s3/__Comtypes.xsd
- schemas/money-s3/__Faktura.xsd
- schemas/money-s3/__Firma.xsd
- schemas/money-s3/__IntDokl.xsd
- schemas/money-s3/__InvDokl.xsd
- schemas/money-s3/__Mzda.xsd
- schemas/money-s3/__Objedn.xsd
- schemas/money-s3/__Seznamy.xsd
- schemas/money-s3/__SklDokl.xsd
- schemas/money-s3/__UcDokl.xsd
- schemas/money-s3/__Uhrady.xsd
- schemas/money-s3/__Zakazka.xsd
- schemas/money-s3/__Zamestnanec.xsd
- schemas/money-s3/__Zasoba.xsd
- weblate_web/invoices/models.py
- weblate_web/invoices/tests.py
- weblate_web/payments/backends.py
> feat: add Money S3 compatible XML export

- weblate_web/tests.py
- weblate_web/views.py
Redirect to completion on already processed payment and do that after selecting for update to make sure previous processing is done.
> fix: gracefully handle double form submission

- weblate_web/invoices/models.py
- weblate_web/payments/backends.py
> feat(backnends): support creating proforma from a draft

- weblate_web/models.py
- weblate_web/payments/models.py
- weblate_web/tests.py
> chore: test and simplify renewal

- weblate_web/invoices/admin.py
- weblate_web/invoices/views.py
- weblate_web/urls.py
- weblate_web/views.py
> feat: add admin invoice download

- weblate_web/invoices/models.py
- weblate_web/invoices/tests.py
- weblate_web/payments/backends.py
> chore: simplify enum naming

- weblate_web/invoices/admin.py
Also hide download link for these.
> fix: do not generate PDF for drafts

- weblate_web/invoices/models.py
We need exact calculations, but do not show unnecessary decimals.
> feat(invoices): reasonably round decimals

- weblate_web/static/custom.js
- weblate_web/templates/payment/customer.html
- weblate_web/templates/payment/payment.html
- weblate_web/templates/snippets/customer_address.html
- weblate_web/templates/snippets/service.html
- weblate_web/templates/user.html
- weblate_web/tests.py
- weblate_web/urls.py
- weblate_web/views.py
Add editing link to user overview.
> feat: allow to edit billing info without payment

- weblate_web/invoices/models.py
- weblate_web/payments/tests.py
- weblate_web/tests.py
- weblate_web/views.py
> feat: use draft invoices for donation

- weblate_web/payments/tests.py
- weblate_web/tests.py
- drop using fakturace where not needed
- switch to thepay2 instead of legacy one
> chore(tests): migrate to use new backend

- weblate_web/payments/backends.py
- weblate_web/views.py
> feat: correctly track invoice category for donations

- weblate_web/tests.py
- weblate_web/views.py
> feat: use invoices for subscriptions

- weblate_web/views.py
> chore: cleanup package tracking in subscriptions

- weblate_web/invoices/models.py
- weblate_web/management/commands/recurring_payments.py
- weblate_web/payments/backends.py
This properly updates package prices and descriptions.
> feat: use invoices to repeat payments

- weblate_web/invoices/models.py
- weblate_web/invoices/templates/invoice-template.html
- weblate_web/invoices/tests.py
- weblate_web/payments/backends.py
> feat: basic support for multiple currencies

- weblate_web/payments/backends.py
- weblate_web/payments/tests.py
We cannot do info and last requests in 30 seconds, so instead introduce new API to fiobank module to return both info at once.
The customization can be removed once https://github.com/honzajavorek/fiobank/pull/38 is released.
Fixes WEBSITE-1Q
> fix: avoid throttling issues with Fio API

- weblate_web/invoices/models.py
- weblate_web/invoices/templates/invoice-template.html
- weblate_web/invoices/tests.py
- weblate_web/invoices/views.py
- weblate_web/payments/backends.py
- weblate_web/payments/models.py
- weblate_web/urls.py
- weblate_web/utils.py
- weblate_web/views.py
This allows to pay manually issued invoices by card.
> feat: add payment link to invoices

- pyproject.toml
- requirements.txt
- weblate_web/invoices/models.py
- weblate_web/invoices/templates/invoice-template.html
- weblate_web/invoices/templates/invoice.css
- weblate_web/invoices/tests.py
> feat(invoices): include payment qrcode

- weblate_web/templates/about.html
> chore: remove myself as provider

- .github/workflows/test.yml
- .gitmodules
- pyproject.toml
- requirements.txt
- weblate_web/payments/backends.py
- weblate_web/payments/tests.py
- weblate_web/tests.py
- update bank backend to not use legacy
- drop legacy code
- drop submodule testing
> feat: update bank backend

- weblate_web/payments/backends.py
- weblate_web/payments/utils.py
> fix: include generated invoices in e-mail

- weblate_web/invoices/tests.py
- weblate_web/payments/backends.py
- weblate_web/views.py
> fix: avoid generating second invoice for direct payment

- weblate_web/invoices/models.py
- weblate_web/pdf.py
> chore: factor out PDF rendering from invoices

- weblate_web/pdf.py
- weblate_web/static/pdf/fonts.css
This way it is easier to maintain and lint.
> chore: move fonts CSS for PDF into a separate file

- weblate_web/invoices/models.py
- weblate_web/invoices/templates/invoice-template.html
- weblate_web/payments/backends.py
> chore: consolidate bank account information

- weblate_web/crm/admin.py
- weblate_web/crm/apps.py
- weblate_web/crm/models.py
- weblate_web/crm/templates/crm/base.html
- weblate_web/crm/templates/crm/index.html
- weblate_web/crm/templates/invoices/invoice_list.html
- weblate_web/crm/templates/weblate_web/service_detail.html
- weblate_web/crm/templates/weblate_web/service_list.html
- weblate_web/crm/tests.py
- weblate_web/crm/urls.py
- weblate_web/crm/views.py
- weblate_web/models.py
- weblate_web/settings.py
- weblate_web/urls.py
- weblate_web/utils.py
- weblate_web/views.py
> Add management views

- weblate_web/hetzner.py
- weblate_web/models.py
> chore: factor out Hetzner API

- weblate_web/hetzner.py
> chore: use contexts to properly close ssh connections

- weblate_web/management/commands/recurring_payments.py
- weblate_web/tests.py
> fix: use same retry policy for donate as subscription

- weblate_web/payments/backends.py
- weblate_web/views.py
> feat: select backends by supported currency

- weblate_web/invoices/models.py
- weblate_web/management/commands/recurring_payments.py
- weblate_web/models.py
- weblate_web/payments/models.py
- weblate_web/tests.py
Manually created ones might not have it, so fill it from scratch.
> fix: consistenly set extra for repeated payments

- weblate_web/payments/backends.py
- weblate_web/payments/tests.py
Improve invoices payment processing and add testcase covering that.
> fix: improve payments processing

- weblate_web/payments/backends.py
> feat: use new fioapi interface instead of reimplementing it

- weblate_web/invoices/models.py
> fix: avoid duplicating invoice items for drafts

- weblate_web/static/style.css
> Clean up deprecated css

- README.rst
- weblate_web/templates/base.html
- weblate_web/tests.py
- weblate_web/urls.py
- make local login work in the UI
- add documentation on how to run this locally
> feat: support local login

- .pre-commit-config.yaml
- pyproject.toml
- saml/attribute-maps/blank.py
- scripts/locales-fixup
- weblate_web/invoices/models.py
- weblate_web/invoices/tests.py
- weblate_web/legal/templates/pdf/dpa.html
- weblate_web/management/commands/recurring_payments.py
- weblate_web/payments/backends.py
- weblate_web/payments/forms.py
- weblate_web/payments/models.py
- weblate_web/payments/utils.py
- weblate_web/pdf.py
- weblate_web/settings.py
- weblate_web/templates/mail/payment_failed.html
- weblate_web/templates/payment/payment.html
- weblate_web/tests.py
- weblate_web/views.py
> feat: introduce codespell

- weblate_web/static/style.css
Make payements form mobile responsive, as well as subscription services in user profile as mentioned in #2504 
Close: #2504
> Make payements form mobile responsive

- weblate_web/static/style.css
Wrap text inside border, the height of the box adapt to its text content.
close: #2516
> Wrap text inside border

- weblate_web/models.py
There should not be concurrent processing of the incoming events.
> fix: select for update on processing payment

- weblate_web/templates/careers.html
> improving the care paragraph

- weblate_web/templates/careers.html
> improving careers page wording and content

- weblate_web/exchange_rates.py
- weblate_web/invoices/models.py
- weblate_web/tests.py
This will allow us to drop fakturace dependency.
> feat: vendor exchange rates fetching

- weblate_web/crm/templates/weblate_web/service_detail.html
- weblate_web/crm/views.py
- weblate_web/forms.py
- weblate_web/models.py
This is no longer used since migration to new legal entity.
> chore: drop legacy invoice import

- weblate_web/views.py
Related to https://github.com/WeblateOrg/weblate/issues/14872
> feat(api): expose information about subscription presence

- weblate_web/management/commands/recurring_payments.py
- weblate_web/models.py
- weblate_web/templates/mail/payment_missing.html
- weblate_web/templates/mail/payment_missing_subject.txt
- weblate_web/templates/mail/payment_upcoming.html
- weblate_web/templates/mail/snippets/donation_info.html
- weblate_web/templates/mail/snippets/subscription_info.html
- weblate_web/tests.py
- include subscription expiry in the e-mail
- use different wording for already expired payments
- improve notification schedule (notify month before yearly renewal, notify few days before the renewal and notify weekly after renewal failed)
See https://github.com/WeblateOrg/weblate/issues/14872
> feat: improve upcoming payment notification

- weblate_web/payments/backends.py
> fix: pass payment currency to the gateway

- weblate_web/templates/snippets/service.html
- weblate_web/templates/user.html
> feat: include card info in user management

- weblate_web/exchange_rates.py
- weblate_web/invoices/models.py
- weblate_web/invoices/tests.py
- weblate_web/templates/mail/snippets/donation_info.html
- weblate_web/templates/mail/snippets/subscription_info.html
- weblate_web/templatetags/prices.py
When user paid in a different currency, the amount was not converted.
> feat: show correct amount in notification e-mails

- weblate_web/invoices/models.py
- weblate_web/management/commands/recurring_payments.py
- weblate_web/models.py
- weblate_web/tests.py
- weblate_web/views.py
> chore: add more type annotations

- weblate_web/crm/templates/payments/customer_merge.html
- weblate_web/crm/tests.py
- weblate_web/crm/views.py
The selected customer will be merged into other to have same behavior as Zammad is merging tickets.
> feat: change customer merge order

- requirements-dev.txt
- requirements.txt
- weblate_web/crm/views.py
- weblate_web/settings.py
> chore: type annotate class views

- weblate_web/crm/templates/invoices/invoice_detail.html
- weblate_web/crm/tests.py
- weblate_web/crm/views.py
- weblate_web/forms.py
- weblate_web/invoices/models.py
- weblate_web/models.py
> feat: add option to convert quote to invoice

- weblate_web/models.py
> fix(invoice): correctly set start date for upgrade invoices

- .github/workflows/test.yml
- weblate_web/forms.py
- weblate_web/tests.py
- weblate_web/views.py
> tests: add test for discovery registration

- .github/workflows/test.yml
- requirements.txt
- weblate_web/settings.py
This tests with more production like environments and prepares for future database migration.
> tests: test with multiple database backends

- .github/renovate.json
- .github/workflows/test.yml
> feat(ci): Pin MariaDB to match production environment

- weblate_web/management/commands/zammad_attachments.py
- weblate_web/management/commands/zammad_sync.py
> chore: use single zammad client configuration

- weblate_web/payments/admin.py
> feat(admin): search payments by uuid
